### ISSUE TITLE
Levenshtein Distance Comutation doesn't work (yet)

### ISSUE THREAD

**Issue by SpechtMagnus** [FIUS/drinklist-cli#51]
The master seems to have a faulty implementation of the levenshtein distance that always return the first beverage in the list.

```
➜ system-and-web-security git:(master) drink Baola
Did you mean Apfelsinensaft? [y/N]
N
```

This might be due to a not yet merged branch. Possibly "https://github.com/FIUS/drinklist-cli/tree/feature/improve-name-correction"

**Comment by marzipankaiser** [comment]
The reason for this was the alias not passing the parameter.
This is fixed in #52.
